# Generated by Django 2.1.7 on 2019-04-30 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(blank=True, null=True)),
                ('iid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cref',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('positionid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('publicvisible', models.BooleanField(blank=True, null=True)),
                ('isavailable', models.BooleanField(blank=True, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('posteddate', models.DateField(blank=True, null=True)),
                ('postingexpirationdate', models.DateField(blank=True, null=True)),
                ('onboardinfo', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=25, null=True)),
                ('companyid', models.ForeignKey(blank=True, db_column='companyid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Company')),
            ],
            options={
                'db_table': 'position',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('iid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pref',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('hashiringpriv', models.BooleanField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=75, null=True)),
                ('joindate', models.DateField(blank=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('iid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uref',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usertable',
            fields=[
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('hashiringpriv', models.BooleanField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=75, null=True)),
                ('joindate', models.DateField(blank=True, null=True)),
                ('companyid', models.ForeignKey(blank=True, db_column='companyid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Company')),
                ('managerid', models.ForeignKey(blank=True, db_column='managerid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Usertable')),
                ('positionid', models.ForeignKey(blank=True, db_column='positionid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Position')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usertable',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='position',
            name='managerid',
            field=models.ForeignKey(blank=True, db_column='managerid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Usertable'),
        ),
        migrations.AddField(
            model_name='company',
            name='ownerid',
            field=models.ForeignKey(blank=True, db_column='ownerid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Usertable'),
        ),
    ]
