# Generated by Django 2.1.7 on 2019-05-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190501_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
